services:
  amd:
    build:
      dockerfile: Dockerfile
    container_name: amd
    stdin_open: true # Garde STDIN ouvert pour une interaction avec le terminal
    volumes:
      - ./app:/app  # Monte le répertoire local ./app dans /app du conteneur
    networks:
      - amd-network

networks:
  amd-network:
    driver: bridge

